using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _movieApp.WebUI.Models
{
    public class Repository
    {
        private static List<Movie> _movies = null;


        static Repository()
        {
            _movies = new List<Movie>()
            {
                new Movie () { ID=1 ,LoadTime = DateTime.Parse("25/11/2019"), CategoryID= 1,Name="Blade Runner", Description=" Blade Runner is a 1982 science fiction film directed by Ridley Scott, and written by Hampton Fancher and David Peoples. Starring Harrison Ford, Rutger Hauer and Sean Young, it is loosely based on Philip K. Dick's novel Do Androids Dream of Electric Sheep? (1968). The film is set in a dystopian future Los Angeles of 2019, in which synthetic humans known as replicants are bio-engineered by the powerful Tyrell Corporation to work on off-world colonies. When a fugitive group of Nexus-6 replicants led by Roy Batty (Hauer) escapes back to Earth, burnt-out cop Rick Deckard (Ford) reluctantly agrees to hunt them down.Blade Runner initially underperformed in North American theaters and polarized critics; some praised its thematic complexity and visuals, while others were displeased with its slow pacing and lack of action. It later became an acclaimed cult film regarded as one of the all - time best science fiction films. Hailed for its production design depicting a \"retrofitted\" future, Blade Runner is a leading example of neo - noir cinema.The soundtrack, composed by Vangelis, was nominated in 1982 for a BAFTA and a Golden Globe as best original score.", ImageUrl="1.jpg"  },
                new Movie () { ID=2 ,LoadTime = DateTime.Parse("25/01/2019"), CategoryID= 3, Name="Tolkien", Description="Tolkien is a 2019 American biographical drama film directed by Dome Karukoski and written by David Gleeson and Stephen Beresford. It is about the early life of English professor J. R. R. Tolkien, author of The Hobbit and The Lord of the Rings, as well as notable academic works. The film stars Nicholas Hoult, Lily Collins, Colm Meaney, and Derek Jacobi.Tolkien was released in the United Kingdom on May 3, 2019 and in the United States on May 10, 2019 by Fox Searchlight Pictures. The film received mixed reviews from critics and grossed $9 million worldwide on a $20 million budget.", ImageUrl="2.jpg"  },
                new Movie () { ID=3 ,LoadTime = DateTime.Parse("05/08/2019"), CategoryID= 2, Name="Road", Description="The Road is a 2009 American post-apocalyptic survival film directed by John Hillcoat and written by Joe Penhall, based on the 2006 novel of the same name by Cormac McCarthy. The film stars Viggo Mortensen and Kodi Smit-McPhee as a father and his son in a post-apocalyptic wasteland.The film received a limited release in North American cinemas from November 25, 2009, and was released in United Kingdom cinemas on January 4, 2010. It received generally positive reviews from critics; the performances of Mortensen and Smit-McPhee garnered praise. It also received numerous nominations, including a BAFTA nomination for Best Cinematography.", ImageUrl="3.jpg"  },
                new Movie () { ID=4 ,LoadTime = DateTime.Parse("15/05/2019"), CategoryID= 1, Name="Venom", Description="Venom is a 2018 American superhero film based on the Marvel Comics character of the same name, produced by Columbia Pictures in association with Marvel and Tencent Pictures. Distributed by Sony Pictures Releasing, it is the first film in Sony's Marvel Universe. Directed by Ruben Fleischer from a screenplay by Jeff Pinkner, Scott Rosenberg, and Kelly Marcel, it stars Tom Hardy as Eddie Brock / Venom, alongside Michelle Williams, Riz Ahmed, Scott Haze, and Reid Scott. In Venom, journalist Brock gains superpowers after being bound to an alien symbiote whose species plans to invade Earth.After Venom appeared in Spider-Man 3 (2007), Sony attempted to develop a spin-off film based on the character. Work began in March 2016 on a new version that would start a new shared universe featuring the Marvel characters that the studio possessed film rights to. Sony also intended for Venom to share the world of the Marvel Cinematic Universe 's Spider-Man: Homecoming (2017), but ultimately distanced the film from Spider-Man. In March 2017, Rosenberg and Pinkner were set to write, with Fleischer and Hardy added in May. Filming took place from that October to January 2018, in Atlanta, New York City, and San Francisco. The film was primarily inspired by the comic book miniseries Venom: Lethal Protector (1993) and the story arc \"Planet of the Symbiotes \" (1995). ", ImageUrl="4.jpg"  },
                new Movie () { ID=5 ,LoadTime = DateTime.Parse("19/06/2019"), CategoryID= 3, Name="Bohemian Rhapsody", Description="Bohemian Rhapsody is a 2018 biographical drama film about Freddie Mercury, the lead singer of the British rock band Queen. It was directed by Bryan Singer from a screenplay by Anthony McCarten, and produced by Graham King and Queen manager Jim Beach. It stars Rami Malek as Mercury, with Lucy Boynton, Gwilym Lee, Ben Hardy, Joe Mazzello, Aidan Gillen, Tom Hollander, Allen Leech, and Mike Myers in supporting roles. Queen members Brian May and Roger Taylor served as consultants. A British-American venture, the film was produced by 20th Century Fox, Regency Enterprises, GK Films, and Queen Films, with Fox serving as distributor. The film follows the singer's life from the formation of the band up to their 1985 Live Aid performance at the original Wembley Stadium. Bohemian Rhapsody was announced in 2010, with Sacha Baron Cohen set to play Mercury. After he left the project in 2013 following creative differences with producers, the project languished for several years before Malek was cast in November 2016.Bryan Singer was the director through most of principal photography, which began in London in September 2017, but was fired in December 2017, for absence and clashing with the cast and crew.Dexter Fletcher, who was originally set to direct the film early in development, was hired to complete the film, although Singer retained sole director credit as per Directors Guild of America guidelines.Fletcher received an executive producer credit and filming concluded in January 2018.", ImageUrl="bohrapso.jpg"  },
                new Movie () { ID=6 ,LoadTime = DateTime.Parse("08/10/2019"), CategoryID= 4, Name="Detective Pikachu", Description="Detective Pikachu (also known as Pokémon Detective Pikachu and released as Great Detective Pikachu in Japan after the original game) is a 2019 urban fantasy mystery film directed by Rob Letterman. Based on the Pokémon franchise created by Satoshi Tajiri and serving as a loose adaptation of the 2016 video game of the same name, it was written by Letterman, Dan Hernandez, Benji Samit and Derek Connolly, from a story by Hernandez, Samit and Nicole Perlman. The film was produced by Legendary Pictures in association with Toho. It is the first live-action Pokémon film. Ryan Reynolds stars as the voice and facial motion capture of Pikachu, with Justice Smith, Kathryn Newton, Suki Waterhouse, Omar Chaparro, Chris Geere, Ken Watanabe and Bill Nighy in live-action roles. Filming took place from January to May 2018 in Colorado, England, and Scotland. It was released in Japan on May 3, 2019, and in the United States on May 10, 2019, distributed by Warner Bros. Pictures in RealD 3D and Dolby Cinema. It is the first Pokémon film to be distributed theatrically in the United States by Warner Bros. since Pokémon 3: The Movie (2001). Detective Pikachu received mixed reviews from critics, who praised the visual effects, creature designs, and Reynolds' performance, but criticized the plot and script as formulaic. With a worldwide gross of over $431 million, it is the second highest-grossing video game film adaptation of all time. Development of a sequel was announced in January 2019, before the release of the film.", ImageUrl="detectivePikachu.jpg"  },
                new Movie () { ID=7 ,LoadTime = DateTime.Parse("11/11/2019"), CategoryID= 4, Name="Dumb And Dumber", Description="Dumb and Dumber is a 1994 American screwball comedy film directed by Peter Farrelly, who co-wrote the screenplay with Bobby Farrelly and Bennett Yellin. Starring Jim Carrey and Jeff Daniels, it tells the story of Lloyd Christmas (Carrey) and Harry Dunne (Daniels), two dumb but well-meaning friends from Providence, Rhode Island, who set out on a cross-country trip to Aspen, Colorado, to return a briefcase full of money to its owner, thinking it was abandoned as a mistake but was actually left as ransom money. Lauren Holly, Karen Duffy, Mike Starr, Charles Rocket, and Teri Garr play supporting roles.The film was released on December 16, 1994. It grossed $247 million at the box office and has developed a cult following in the years since its release. The success of Dumb and Dumber launched the career of the Farrelly brothers and solidified Carrey's. The film also spawned an animated TV series, a 2003 prequel, and a 2014 sequel.", ImageUrl="dumbanddumber.jpg"  },
                new Movie () { ID=8 ,LoadTime = DateTime.Parse("28/11/2019"), CategoryID= 1, Name="Interstellar", Description="Interstellar is a 2014 British-American epic science fiction film directed and produced by Christopher Nolan. It stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, and Michael Caine. Set in a dystopian future where humanity is struggling to survive, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for humanity.Brothers Christopher and Jonathan Nolan wrote the screenplay, which had its origins in a script Jonathan developed in 2007. Christopher produced Interstellar with his wife, Emma Thomas, through their production company Syncopy, and with Lynda Obst through Lynda Obst Productions. Caltech theoretical physicist Kip Thorne was an executive producer, acted as scientific consultant, and wrote a tie-in book, The Science of Interstellar. Paramount Pictures, Warner Bros., and Legendary Pictures co-financed the film. Cinematographer Hoyte van Hoytema shot it on 35 mm in anamorphic format and IMAX 70 mm. Principal photography began in late 2013 and took place in Alberta (Canada), Iceland and Los Angeles. Interstellar uses extensive practical and miniature effects and the company Double Negative created additional digital effects.Interstellar premiered on October 26, 2014, in Los Angeles, California. In the United States, it was first released on film stock, expanding to venues using digital projectors. The film had a worldwide gross of over $677 million, making it the tenth-highest - grossing film of 2014.Interstellar received critical praise for its themes, visual effects, musical score, and acting.At the 87th Academy Awards, the film won the Academy Award for Best Visual Effects, and was nominated for Best Original Score, Best Sound Mixing, Best Sound Editing and Best Production Design.", ImageUrl="interstellar.jpg"  },
                new Movie () { ID=9 ,LoadTime = DateTime.Parse("15/07/2019"), CategoryID= 2, Name="Intouchables ", Description="The Intouchables (French: Intouchables [ɛ̃tuʃabl]), also known as Untouchable (UK), is a 2011 French buddy comedy-drama film directed by Olivier Nakache & Éric Toledano. It stars François Cluzet and Omar Sy. Nine weeks after its release in France on 2 November 2011, it became the second biggest box office hit in France, just behind the 2008 film Welcome to the Sticks. The film was voted the cultural event of 2011 in France with 52% of votes in a poll by Fnac. It also became the most viewed French film in the world with 51,5 million tickets up to 2014 and the success of Lucy. The film has received several award nominations. In France, the film won the César Award for Best Actor for Omar Sy, and garnered seven further nominations for the César Awards, including the César Award for Best Film.", ImageUrl="intouchbeles.jpg"  },
                new Movie () { ID=10 ,LoadTime = DateTime.Parse("08/07/2019"), CategoryID= 4, Name="Lego Movie 2 ", Description="The Lego Movie 2: The Second Part is a 2019 computer-animated adventure comedy film produced by the Warner Animation Group and distributed by Warner Bros. Pictures. Directed by Mike Mitchell, it is a direct sequel to The Lego Movie (2014) and the fourth film in the franchise following the releases of 2017's The Lego Batman Movie and The Lego Ninjago Movie. The film stars Chris Pratt, Elizabeth Banks, Will Arnett, Charlie Day, Alison Brie, Nick Offerman, and Will Ferrell reprising their roles from the previous film, whilst new cast members include Tiffany Haddish, Stephanie Beatriz, and Maya Rudolph (replacing Amanda Farinos). In the film, Emmet Brickowski attempts to rescue his friends from the Systar System, while dealing with a coming cataclysm known as \"Armamageddon\". Plans for a sequel began in 2014 and was announced to be in the works on February 3, 2014, a few days before the release of the first film.It was announced a few months later that the film was being directed by Chris McKay while Phil Lord and Christopher Miller remained as producers.The film since underwent many changes, such as rewrites, directors, and release dates. The Lego Movie 2: The Second Part was released in the United States and United Kingdom on February 8, 2019, in 2D, 3D, RealD 3D, Dolby Cinema, IMAX, and IMAX 3D formats.It received generally positive reviews from critics, who commended its humor, animation, soundtrack, and voice acting, although some said it was not as \"fresh\" as the first film. With a worldwide gross of over $191 million worldwide against a budget of $99 million, the film underperformed at the box office compared to the first three films in the series.", ImageUrl="legomovie.jpg"  },
                new Movie () { ID=11 ,LoadTime = DateTime.Parse("18/03/2019"), CategoryID= 3, Name="Rocketman ", Description="Rocketman is a 2019 biographical musical film based on the life of musician Elton John. Directed by Dexter Fletcher and written by Lee Hall, it stars Taron Egerton as John, with Jamie Bell as Bernie Taupin, Richard Madden as John Reid, and Bryce Dallas Howard as Sheila Eileen. The film follows John in his early days as a prodigy at the Royal Academy of Music through his musical partnership with Taupin. The film is titled after John's 1972 song \"Rocket Man.\". The film had been in development since the 2000s before it was initially announced in 2013 where Focus Features acquired the rights to the film and director Michael Gracey and actor Tom Hardy were set to direct and star in the project respectively. After Hardy and Gracey left the project following creative differences between Focus and John that halted an initial production start in fall 2014, the project languished for several years until Paramount Pictures and New Republic Pictures took over as distributor in April 2018, where Egerton and Fletcher signed on.Principal photography began in August 2018 and was completed later that year.John served as executive producer, while husband David Furnish produced the film through their Rocket Pictures, alongside Matthew Vaughn's Marv Films. Rocketman premiered at the Cannes Film Festival on 16 May 2019, and was theatrically released in the United Kingdom on 22 May 2019 and in the United States on 31 May 2019.It grossed $195 million worldwide against its $40 million budget and received largely positive reviews from critics, with general praise for Egerton's performance, the costume design and musical numbers. The film was the first by a major film studio to include a gay male sex scene.", ImageUrl="rocketman.jpg"  },
                new Movie () { ID=12 ,LoadTime = DateTime.Parse("07/05/2019"), CategoryID= 2, Name="Schindler's List ", Description="Schindler's List is a 1993 American historical period drama film directed and co-produced by Steven Spielberg and written by Steven Zaillian. It is based on the novel Schindler's Ark by Australian novelist Thomas Keneally. The film follows Oskar Schindler, a Sudeten German businessman, who saved more than a thousand mostly Polish-Jewish refugees from the Holocaust by employing them in his factories during World War II. It stars Liam Neeson as Schindler, Ralph Fiennes as SS officer Amon Göth, and Ben Kingsley as Schindler's Jewish accountant Itzhak Stern. Ideas for a film about the Schindlerjuden(Schindler Jews) were proposed as early as 1963.Poldek Pfefferberg, one of the Schindlerjuden, made it his life\'s mission to tell Schindler\'s story.Spielberg became interested when executive Sidney Sheinberg sent him a book review of Schindler's Ark. Universal Pictures bought the rights to the novel, but Spielberg, unsure if he was ready to make a film about the Holocaust, tried to pass the project to several directors before deciding to direct it. Principal photography took place in Kraków, Poland, over 72 days in 1993.Spielberg shot in black and white and approached the film as a documentary.Cinematographer Janusz Kamiński wanted to create a sense of timelessness.John Williams composed the score, and violinist Itzhak Perlman performed the main theme. Schindler\'s List premiered on November 30, 1993, in Washington, D.C. and was released on December 15, 1993, in the United States. Often listed among the greatest films ever made, it was also a box office success, earning $322 million worldwide on a $22 million budget. It was nominated for twelve Academy Awards, winning seven, including Best Picture, Best Director, Best Adapted Screenplay, and Best Original Score, and won numerous other awards, including seven BAFTAs and three Golden Globes. In 2007, the American Film Institute ranked Schindler\'s List 8th on its list of the 100 best American films of all time.The Library of Congress", ImageUrl="schindlers-list-poster.jpg"  },


            };
        }

        public static List<Movie> Movies
        {
            get
            {
                return _movies;
            }
        }

        public static void AddMovie(Movie entity)
        {
            _movies.Add(entity);
        }

        public static Movie GetByID(int id)
        {
            return _movies.FirstOrDefault(i => i.ID == id);
        }
    }
}
